#!/usr/bin/env bash
set -euo pipefail

echo "=========================================="
echo "  Agent Architecture — Setup"
echo "=========================================="

# ---------------------------------------------------------------------------
# 1. Python version check
# ---------------------------------------------------------------------------
PYTHON_CMD="${PYTHON_CMD:-python3}"
if ! command -v "$PYTHON_CMD" &>/dev/null; then
    echo "ERROR: python3 not found. Install Python 3.11+ and try again."
    exit 1
fi

PY_MAJOR=$($PYTHON_CMD -c "import sys; print(sys.version_info.major)")
PY_MINOR=$($PYTHON_CMD -c "import sys; print(sys.version_info.minor)")
if [[ "$PY_MAJOR" -lt 3 || ("$PY_MAJOR" -eq 3 && "$PY_MINOR" -lt 11) ]]; then
    echo "ERROR: Python $PY_MAJOR.$PY_MINOR is too old. Python 3.11+ is required."
    exit 1
fi
echo "OK: Python $PY_MAJOR.$PY_MINOR"

# ---------------------------------------------------------------------------
# 2. Postgres client check
# ---------------------------------------------------------------------------
if ! command -v psql &>/dev/null; then
    echo "WARNING: psql (Postgres client) not found."
    echo "  macOS: brew install postgresql@17"
    echo "  Ubuntu: sudo apt install postgresql-client"
    echo ""
    read -rp "Continue anyway? [y/N] " ans
    [[ "$ans" =~ ^[Yy]$ ]] || exit 1
else
    echo "OK: psql found"
fi

# ---------------------------------------------------------------------------
# 3. Virtual environment
# ---------------------------------------------------------------------------
VENV_DIR="${VENV_DIR:-.venv}"
if [[ ! -d "$VENV_DIR" ]]; then
    echo "Creating virtual environment in $VENV_DIR ..."
    "$PYTHON_CMD" -m venv "$VENV_DIR"
fi
source "$VENV_DIR/bin/activate"
echo "OK: venv activated"

# ---------------------------------------------------------------------------
# 4. Install dependencies
# ---------------------------------------------------------------------------
echo "Installing Python dependencies ..."
pip install -q --upgrade pip
pip install -q -r requirements.txt

# ---------------------------------------------------------------------------
# 5. Prompt for environment variables
# ---------------------------------------------------------------------------
echo ""
echo "--- Configuration ---"
echo "Press Enter to accept the default shown in [brackets]."
echo ""

prompt() {
    local var_name="$1"
    local default="$2"
    local value
    read -rp "$var_name [$default]: " value
    echo "${value:-$default}"
}

ACTOR_ID=$(prompt "ACTOR_ID" "owner:$(whoami)")
TELEGRAM_USER_ID=$(prompt "TELEGRAM_USER_ID" "")
DATABASE_URL=$(prompt "DATABASE_URL" "postgresql:///agent_memory")
TELEGRAM_BOT_TOKEN=$(prompt "TELEGRAM_BOT_TOKEN" "")

cat > .env <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
DATABASE_URL=$DATABASE_URL
CHECKPOINTER=postgres
MEMORY_BACKEND=postgres

ACTOR_ID=$ACTOR_ID
TELEGRAM_USER_ID=$TELEGRAM_USER_ID
TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN

EMBEDDING_PROVIDER=local
LOCAL_EMBEDDING_MODEL=all-MiniLM-L6-v2
EOF

echo "OK: wrote .env"

# ---------------------------------------------------------------------------
# 6. Run schema migration
# ---------------------------------------------------------------------------
echo ""
echo "Running init_schema.sql ..."
if psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f init_schema.sql >/dev/null 2>&1; then
    echo "OK: schema applied"
else
    echo "WARNING: schema migration failed."
    echo "  Make sure Postgres is running and the database exists:"
    echo "    createdb agent_memory"
    echo "  Then re-run:"
    echo "    psql \"$DATABASE_URL\" -f init_schema.sql"
fi

# ---------------------------------------------------------------------------
# 7. SkillLoop project init (best-effort)
# ---------------------------------------------------------------------------
echo ""
if python -m skillloop.cli --help &>/dev/null; then
    echo "Initializing SkillLoop project state ..."
    python -m skillloop.cli --path . init || true
    python -m skillloop.cli --path . setup --connect hermes || true
    echo "OK: SkillLoop initialized"
else
    echo "NOTE: skillloop CLI not found."
    echo "  If you have SkillLoop installed elsewhere, run:"
    echo "    skillloop --path . init"
    echo "    skillloop --path . setup --connect hermes"
fi

# ---------------------------------------------------------------------------
# 8. Done
# ---------------------------------------------------------------------------
echo ""
echo "=========================================="
echo "  Setup complete"
echo "=========================================="
echo ""
echo "Next steps:"
echo "  1. Review .env and add any missing secrets (LLM_API_KEY, etc.)"
echo "  2. Set up launchd plists or cron for the hourly jobs — see README.md"
echo "  3. Run smoke tests:"
echo "       python -B smoke_test.py"
echo "  4. Run the test suite:"
echo "       python -B -m pytest -p no:cacheprovider src -q"
echo ""
